---
title: '2023'
author: "Owen Fiore"
date: "2023-08-29"
output: pdf_document
---

```{r}
new <- read.csv("../Data/Thesis2023.csv")
colnames(new) <- c("Year", "Type", "Time", "RxnTime", "Gender", "Batch")

men_new_pooled <- subset(new, (Type == "F" | Type == "S") & Gender == "M" & (Time != 'DQ' | Time != 'DNF'))
```

```{r}
library(ggplot2)
ggplot(men_new_pooled, aes(x = Year, y = RxnTime, group = Year)) +
  geom_boxplot(fill = "orange1", color = "orangered4") +
  labs(x = "Year", y = "Reaction Time (s)") +
       scale_y_continuous(limits = c(0.1, 0.225),
                            breaks = seq(0.1, 0.225, 0.025)) +
  expand_limits(y = 0.1) + scale_x_continuous(limits = c(1998,2024),
                                              breaks = seq(1997, 2024, 2))
```
```{r}
library(lme4)
men_new_pooled_one_gamma_log <- glm(RxnTime ~ 1, data = men_new_pooled, 
                                family = Gamma(link = "log"))

men_new_pooled_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_new_pooled, 
                                       family = Gamma(link = "log"))
men_new_pooled_batch_gamma_log <- glmer(RxnTime ~ (1|Batch), data = men_new_pooled, 
                                       family = Gamma(link = "log"))
men_new_pooled_two_effect_gamma_log <- glmer(RxnTime ~ (1 | Year) + (1 | Batch), 
                                   data = men_new_pooled, family = Gamma(link = "log"))
```
```{r}
set.seed(1)
library(lme4)
sim_two_effect_time <- function(model, base, RxnTime) {
  simfit <- function(model, n = 10000000) {
    vc <- as.data.frame(VarCorr(model))
    sd_year <- vc$sdcor[1]
    sd_year_batch <- vc$sdcor[2]
    
    z1 <- rnorm(n, sd = sd_year)
    z2 <- rnorm(n, sd = sd_year_batch)
    
    shape <- 1 / sigma(model)^2
    mu <- exp(fixef(model) + z1 + z2)
    
    x <- rgamma(n, shape = shape, scale = mu / shape)
    x
  }
  
  sbase <- summary(base)
  x <- simfit(model)
  print(mean(x < RxnTime))
  #print(quantile(x, prob = c(0.00001, 0.0001, 0.0005, 0.001)))
  ## compare with and without random effect
  plot(density(x))  # with random effects
  curve(dgamma(x, shape = 1 / sbase$dispersion, 
               scale = exp(coef(base)) * sbase$dispersion), 
        0.08, 0.25, add = TRUE, col = "blue")  # fixed effect only
}
```

```{r}
sim_two_effect_time(men_new_pooled_two_effect_gamma_log, men_new_pooled_one_gamma_log, 0.1)
```
```{r}
comp <- read.csv("../Data/Clusrank2022vs2023.csv")
colnames(comp) <- c("Time", "Athlete", "Year")
```

```{r}
library(clusrank)
clusWilcox.test(Time, group=Year, cluster = Athlete, data = comp,
                method = "ds")

clusWilcox.test(Time, group=Year, cluster = Athlete, data = comp,
                method = "ds",
                exact = TRUE, B = 10000)
```



