---
title: "Random_Effects"
author: "Owen Fiore"
date: "2023-05-31"
output: pdf_document
---


Clearn it up: two_effect and nested are the same model. Don't confuse the readers.

Keep the code styles (80 characters linewidth; etc.)

Add text between the code chunks to document what you are doing.


```{r}
times <- read.csv("../Data/ThesisData.csv")
colnames(times) <- c("Year", "Type", "Time", "RxnTime", "Gender", "Batch")
men_finals <- subset(times, Type == "F" & Gender == "M" & Time != 'DQ') # & Year < 2022)
men_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "M" & Time != 'DQ')
men_old_finals <- subset(times, Type == "F" & Gender == "M" & Time != 'DQ' & Year < 2022)
men_old_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "M" & Time != 'DQ' & Year < 2022)
```
```{}
This loads in the datasets
```



```{r}
library(lme4)
men_old_finals_one_gamma_log <- glm(RxnTime ~ 1, data = men_old_finals, family = Gamma(link = "log"))
men_old_finals_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_old_finals, family = Gamma(link = "log"))

men_finals_one_gamma_log <- glm(RxnTime ~ 1, data = men_finals, family = Gamma(link = "log"))
men_finals_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_finals, family = Gamma(link = "log"))

men_old_pooled_one_gamma_log <- glm(RxnTime ~ 1, data = men_old_pooled, family = Gamma(link = "log"))
men_old_pooled_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_old_pooled, family = Gamma(link = "log"))

men_pooled_one_gamma_log <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))
men_pooled_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_pooled, family = Gamma(link = "log"))

```
```{}
This creates the year effect and the no year effect models
```


```{r}
men_old_finals_batch <-glmer(RxnTime ~ (1 | Batch), data = old_finals, family = Gamma(link = "log"))
men_finals_batch <-glmer(RxnTime ~ (1 | Batch), data = men_finals, family = Gamma(link = "log"))
men_old_pooled_batch <-glmer(RxnTime ~ (1 | Batch), data = old_pooled, family = Gamma(link = "log"))
men_pooled_batch <-glmer(RxnTime ~ (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
```
```{}
This creates the batch effect only models
```



```{r}
men_old_finals_two_effect <- glmer(RxnTime ~ (1 | Year) + (1 | Batch), data = old_finals, family = Gamma(link = "log"))
men_finals_two_effect<- glmer(RxnTime ~ (1 | Year) + (1 | Batch), data = men_finals, family = Gamma(link = "log"))
men_old_pooled_two_effect <- glmer(RxnTime ~ (1 | Year) + (1 | Batch), data = old_pooled, family = Gamma(link = "log"))
men_pooled_two_effect <- glmer(RxnTime ~ (1 | Year) + (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
```
```{}
This creates the year and batch effect models
```



```{r}
anova(men_pooled_batch, men_pooled_two_effect)
```
```{}
This anova test determined that the two_effect model is an improvement over the
batch effect model. The test statistic is significant at alpha = 0.05 but not at
alpha = 0.01.
```




```{r}
anova(men_pooled_year_gamma_log, men_pooled_two_effect)
```
```{}
In this anova test, it is clear that the two random effect model is superior to
having only the year effect.
```


```{r}
set.seed(1)
library(lme4)
simulation_two_effect <- function(model, base, RxnTime) {
  simfit <- function(model, n = 10000000) {
    vc <- as.data.frame(VarCorr(model))
    sd_year <- vc$sdcor[1]
    sd_year_batch <- vc$sdcor[2]
    
    z1 <- rnorm(n, sd = sd_year)
    z2 <- rnorm(n, sd = sd_year_batch)
    
    shape <- 1 / sigma(model)^2
    mu <- exp(fixef(model) + z1 + z2)
    
    x <- rgamma(n, shape = shape, scale = mu / shape)
    x
  }
  
  sbase <- summary(base)
  x <- simfit(model)
  print(mean(x < RxnTime))
  #print(quantile(x, prob = c(0.00001, 0.0001, 0.0005, 0.001)))
  ## compare with and without random effect
  plot(density(x))  # with random effects
  curve(dgamma(x, shape = 1 / sbase$dispersion, 
               scale = exp(coef(base)) * sbase$dispersion), 
        0.08, 0.22, add = TRUE, col = "blue")  # fixed effect only
}
simulation_two_effect(old_finals_two_effect, old_finals_one_gamma_log, 0.1)
simulation_two_effect(men_finals_two_effect, men_finals_one_gamma_log, 0.1)
simulation_two_effect(old_pooled_two_effect, old_pooled_one_gamma_log, 0.1)
simulation_two_effect(men_pooled_two_effect, men_pooled_one_gamma_log, 0.1)
```


```{}
This code simulates the probability of observing a reaction time less than 0.1
for the various datasets.
```


```{r}
library(lme4)
set.seed(1)
simulation_one_effect <- function(model, base, RxnTime){
    simfit <- function(model, n = 10000000) {
    vc <- as.data.frame(VarCorr(model))
    ## mu <- exp(coef(model)$Year[,]) ## using fitted random effects only
    z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
    mu <- exp(fixef(model) + z)
    shape <- 1 / vc$vcov[2]
    x <- rgamma(n, shape = shape, scale = mu / shape)
    x
    }
  sbase <- summary(base)
  #print(sbase)
  x <- simfit(model)
  print(mean(x < RxnTime))
  #print(quantile(x, prob = c(.00001, .0001, .0005, .001)))
  ## compare with and without random effect
  plot(density(x)) # with random effect
  curve(dgamma(x, shape = 1 / sbase$dispersion, 
               scale = exp(coef(base)) * sbase$dispersion), 
        0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
}
simulation_one_effect(old_finals_year_gamma_log, old_finals_one_gamma_log, 0.1)
simulation_one_effect(men_finals_year_gamma_log, men_finals_one_gamma_log, 0.1)
simulation_one_effect(old_pooled_year_gamma_log, old_pooled_one_gamma_log, 0.1)
simulation_one_effect(men_pooled_year_gamma_log, men_pooled_one_gamma_log, 0.1)
```

```{}
The above code simulates the probability of observing a reaction time less than
0.1 seconds for the year effect model.
```


```{}
All probabilities are for RxnTime=0.1 seconds
old finals: 0.0004356 vs 0.0004389
men_finals: 0.0008642 vs 0.0008626
old pooled: 0.0041495 vs 0.0057287
men_pooled: 0.005145 vs 0.0068441
The times on the left are for the 2 batch, times on the right are for the 1 batch

Thus if we want to pick the model with the larger probabilities to show that 
0.01 is not extreme, the one random effect probabilities are slightly smaller.
```

