---
title: "Models"
author: "Owen Fiore"
date: "2023-02-07"
output: pdf_document
---

```{r}
times <- read.csv("../Data/ThesisData.csv")
colnames(times) <- c("Year", "Type", "Time", "RxnTime", "Gender", "Batch")
```

```{r}
men_finals <- subset(times, Type == "F" & Gender == "M" & Time != 'DQ') # & Year < 2022)
men_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "M" & Time != 'DQ')
```

```{r}
men_old_finals <- subset(times, Type == "F" & Gender == "M" & Time != 'DQ' & Year < 2022)
men_old_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "M" & Time != 'DQ' & Year < 2022)
```

```{r}
library(lme4)
men_finals_one <- glm(RxnTime ~ 1, data = men_finals)
men_finals_year <- lmer(RxnTime ~ (1|Year), data = men_finals)
men_finals_one_gamma <- glm(RxnTime ~ 1, data = men_finals, family = Gamma)
men_finals_year_gamma <- glmer(RxnTime ~ (1|Year), data = men_finals, family = Gamma)
men_finals_one_gamma_log <- glm(RxnTime ~ 1, data = men_finals, family = Gamma(link = "log"))
men_finals_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_finals, family = Gamma(link = "log"))

paste("Linear without year effect has AIC of", AIC(men_finals_one), "and log-lik of", logLik(men_finals_one))
paste("Linear with year effect has AIC of", AIC(men_finals_year), "and log-lik of", logLik(men_finals_year))
paste("Gamma without year effect has AIC of", AIC(men_finals_one_gamma), "and log-lik of", logLik(men_finals_one_gamma))
paste("Gamma with year effect has AIC of", AIC(men_finals_year_gamma), "and log-lik of", logLik(men_finals_year_gamma))
paste("Gamma and log without year effect has AIC of", AIC(men_finals_one_gamma_log), "and log-lik of", logLik(men_finals_one_gamma_log))
paste("Gamma and log with year effect has AIC of", AIC(men_finals_year_gamma_log), "and log-lik of", logLik(men_finals_year_gamma_log))
```

```{}
The best selected model is men_finals_year_gamma as that has the smallest AIC: -491 and largest log-lik of 248.5
```


```{r}
library(lme4)
men_old_finals_one <- glm(RxnTime ~ 1, data = men_old_finals)
men_old_finals_year <- lmer(RxnTime ~ (1|Year), data = men_old_finals)
men_old_finals_one_gamma <- glm(RxnTime ~ 1, data = men_old_finals, family = Gamma)
men_old_finals_year_gamma <- glmer(RxnTime ~ (1|Year), data = men_old_finals, family = Gamma)
men_old_finals_one_gamma_log <- glm(RxnTime ~ 1, data = men_old_finals, family = Gamma(link = "log"))
men_old_finals_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_old_finals, family = Gamma(link = "log"))

paste("Linear without year effect has AIC of", AIC(men_old_finals_one), "and log-lik of", logLik(men_old_finals_one))
paste("Linear with year effect has AIC of", AIC(men_old_finals_year), "and log-lik of", logLik(men_old_finals_year))
paste("Gamma without year effect has AIC of", AIC(men_old_finals_one_gamma), "and log-lik of", logLik(men_old_finals_one_gamma))
paste("Gamma with year effect has AIC of", AIC(men_old_finals_year_gamma), "and log-lik of", logLik(men_old_finals_year_gamma))
paste("Gamma and log without year effect has AIC of", AIC(men_old_finals_one_gamma_log), "and log-lik of", logLik(men_old_finals_one_gamma_log))
paste("Gamma and log with year effect has AIC of", AIC(men_old_finals_year_gamma_log), "and log-lik of", logLik(men_old_finals_year_gamma_log))
```
```{}
The best selected model is men_old_finals_year_gamma as that has the smallest AIC: -465 and largest log-lik of 235.5.  The models for the older data does not seem to fit the data as good as for the full data set.
```

```{r}
library(lme4)
men_pooled_one <- glm(RxnTime ~ 1, data = men_pooled)
men_pooled_year <- lmer(RxnTime ~ (1|Year), data = men_pooled)
men_pooled_one_gamma <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma)
men_pooled_year_gamma <- glmer(RxnTime ~ (1|Year), data = men_pooled, family = Gamma)
men_pooled_one_gamma_log <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))
men_pooled_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_pooled, family = Gamma(link = "log"))

paste("Linear without year effect has AIC of", AIC(men_pooled_one), "and log-lik of", logLik(men_pooled_one))
paste("Linear with year effect has AIC of", AIC(men_pooled_year), "and log-lik of", logLik(men_pooled_year))
paste("Gamma without year effect has AIC of", AIC(men_pooled_one_gamma), "and log-lik of", logLik(men_pooled_one_gamma))
paste("Gamma with year effect has AIC of", AIC(men_pooled_year_gamma), "and log-lik of", logLik(men_pooled_year_gamma))
paste("Gamma and log without year effect has AIC of", AIC(men_pooled_one_gamma_log), "and log-lik of", logLik(men_pooled_one_gamma_log))
paste("Gamma and log with year effect has AIC of", AIC(men_pooled_year_gamma_log), "and log-lik of", logLik(men_pooled_year_gamma_log))
```
```{}
The best selected model is men_pooled_year_gamma_log as it had the smallest AIC and the largest log-lik
```

```{r}
library(lme4)
men_old_pooled_one <- glm(RxnTime ~ 1, data = men_old_pooled)
men_old_pooled_year <- lmer(RxnTime ~ (1|Year), data = men_old_pooled)
men_old_pooled_one_gamma <- glm(RxnTime ~ 1, data = men_old_pooled, family = Gamma)
men_old_pooled_year_gamma <- glmer(RxnTime ~ (1|Year), data = men_old_pooled, family = Gamma)
men_old_pooled_one_gamma_log <- glm(RxnTime ~ 1, data = men_old_pooled, family = Gamma(link = "log"))
men_old_pooled_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_old_pooled, family = Gamma(link = "log"))

paste("Linear without year effect has AIC of", AIC(men_old_pooled_one), "and log-lik of", logLik(men_old_pooled_one))
paste("Linear with year effect has AIC of", AIC(men_old_pooled_year), "and log-lik of", logLik(men_old_pooled_year))
paste("Gamma without year effect has AIC of", AIC(men_old_pooled_one_gamma), "and log-lik of", logLik(men_old_pooled_one_gamma))
paste("Gamma with year effect has AIC of", AIC(men_old_pooled_year_gamma), "and log-lik of", logLik(men_old_pooled_year_gamma))
paste("Gamma and log without year effect has AIC of", AIC(men_old_pooled_one_gamma_log), "and log-lik of", logLik(men_old_pooled_one_gamma_log))
paste("Gamma and log with year effect has AIC of", AIC(men_old_pooled_year_gamma_log), "and log-lik of", logLik(men_old_pooled_year_gamma_log))
```
```{}
The best model is men_old_pooled_year_gamma as that has the smallest AIC: -1687.5 and the largest log-lik: 846.8
```





```{}
Simulate to see what prob of a time less than 0.1 second rxn time.
```


##Simulations


```{r}
library(lme4)
men_pooled_gamma_year <- glmer(RxnTime ~ (1 | Year), data = men_pooled, family = Gamma(link = "log"))
baseline <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))

simfit <- function(men_pooled_gamma_year, n = 12000000) {
  vc <- as.data.frame(VarCorr(men_pooled_gamma_year))
  ## mu <- exp(coef(men_pooled_gamma_year)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(men_pooled_gamma_year) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
}
sbaseline <- summary(baseline)
#print(sbaseline)
x <- simfit(men_pooled_gamma_year)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x)) # with random effect
curve(dgamma(x, shape = 1 / sbaseline$dispersion,
             scale = exp(coef(baseline)) * sbaseline$dispersion),
      0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
```

```{r}
set.seed(1)
simulation <- function(model, base){
    simfit <- function(model, n = 10000000) {
    vc <- as.data.frame(VarCorr(model))
    ## mu <- exp(coef(model)$Year[,]) ## using fitted random effects only
    z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
    mu <- exp(fixef(model) + z)
    shape <- 1 / vc$vcov[2]
    x <- rgamma(n, shape = shape, scale = mu / shape)
    x
    }
  sbase <- summary(base)
  #print(sbase)
  x <- simfit(model)
  print(mean(x < 0.08))
  print(quantile(x, prob = c(.00001, .0001, .0005, .001)))
  ## compare with and without random effect
  plot(density(x)) # with random effect
  curve(dgamma(x, shape = 1 / sbase$dispersion, 
               scale = exp(coef(base)) * sbase$dispersion), 
        0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
}
simulation(old_pooled_year_gamma_log, old_pooled_one_gamma_log)
```


```{}
Every 1000 racers, we expect 7 to have a reaction time below 0.1 seconds.  If we want 1 out of every 1000
```


##2019 vs 2022 Comparisons
```{r}
comp <- read.csv("../Data/Clusrank2019vs2022.csv")
#"C:\Users\ofior\Documents\Thesis\Data\2019vs2022.csv"
colnames(comp) <- c("Time", "Athlete", "Year")
#View(comp)
```

```{}
One thing that we discovered is that including group=Year does not effect the the z score or p value.  Changing the method from
rgl to ds does effect z score.
```


```{r}
library(clusrank)
clusWilcox.test(Time, group=Year, cluster = Athlete, data = comp, alternative = "greater", method = "ds")
#clusWilcox.test(Time, group=Year, cluster = Athlete, data = comp, alternative = "greater", method = "rgl")
#pairwise.clusWilcox.test(comp$Time, group= comp$Year, cluster = comp$Athlete, alternative = "greater", method = "rgl")
```


```{r}
nations <- read.csv("../Data/ClusrankNatvsWorld.csv")
colnames(nations) <- c("Time", "Athlete", "Year")
```

```{r}
library(clusrank)
clusWilcox.test(Time, group=Year, cluster = Athlete, data = nations, alternative = "greater", method = "ds")
#clusWilcox.test(Time, group=Year, cluster = Athlete, data = nations, paired = TRUE, alternative = "greater", method = "rgl")

```

```{}
In both examples, rgl produced a smaller p value
```

```{r}
mini <- min(aggregate(times$RxnTime, list(times$Batch), FUN =mean)$x)
maxi <- max(aggregate(times$RxnTime, list(times$Batch), FUN =mean)$x)
cat(maxi - mini)
```

#Trying out identity link
```{r}
men_finals_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_finals, family = Gamma(link = "log"))
t1 <- glmer(RxnTime ~ (1|Year), data = men_finals, family = Gamma(link = "identity"))
paste("Gamma and log with year effect has AIC of", AIC(men_finals_year_gamma_log), "and log-lik of", logLik(men_finals_year_gamma_log))
paste("Linear without year effect has AIC of", AIC(t1), "and log-lik of", logLik(t1))
```

```{r}
men_old_finals_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_old_finals, family = Gamma(link = "log"))
t2 <- glmer(RxnTime ~ (1|Year), data = men_old_finals, family = Gamma(link = "identity"))
paste("Linear without year effect has AIC of", AIC(men_old_finals_year_gamma_log), "and log-lik of", logLik(men_old_finals_year_gamma_log))
paste("Linear without year effect has AIC of", AIC(t2), "and log-lik of", logLik(t2))
```

```{r}
men_pooled_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_pooled, family = Gamma(link = "log"))
t3 <- glmer(RxnTime ~ (1|Year), data = men_pooled, family = Gamma(link = "identity"))
paste("Gamma and log with year effect has AIC of", AIC(men_pooled_year_gamma_log), "and log-lik of", logLik(men_pooled_year_gamma_log))
paste("Linear without year effect has AIC of", AIC(t3), "and log-lik of", logLik(t3))
```

```{r}
men_old_pooled_year_gamma_log <- glmer(RxnTime ~ (1|Year), data = men_old_pooled, family = Gamma(link = "log"))
t4 <- glmer(RxnTime ~ (1|Year), data = men_old_pooled, family = Gamma(link = "identity"))
paste("Gamma and log with year effect has AIC of", AIC(men_old_pooled_year_gamma_log), "and log-lik of", logLik(men_old_pooled_year_gamma_log))
paste("Linear without year effect has AIC of", AIC(t4), "and log-lik of", logLik(t4))

```

