---
title: "Plots"
author: "Owen Fiore"
date: "2022-12-09"
output: html_document
---

```{r}
times <- read.csv("../Data/ThesisData.csv")
## View(times)
colnames(times) <- c("Year", "Type", "Time", "RxnTime", "Gender", "Batch")
```

#DataSets
```{r}
men_finals <- subset(times, Type == "F" & Gender == "M" & Time != 'DQ') # & Year < 2022)
women_finals <- subset(times, Type == "F" & Gender == "F" & Time != 'DQ')

men_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "M" & Time != 'DQ')
women_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "F" & Time != 'DQ')
```

#Models
```{r}
library(lme4)
finals.lme <- lmer(RxnTime ~ (1|Year), data = men_pooled)
```

###Functions
```{r}
simfit <- function(fit2, n = 12000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x)) # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
```

#Figures
```{r}
pdf(file = "TBY.pdf")
plot(aggregate(men_pooled$RxnTime, list(men_pooled$Year), FUN = mean), xlab = "Year", ylab = "Reaction time in seconds", main = "Mean Reaction Time By Year")
dev.off()
```

```{r}
pdf(file = "Skew.pdf")
hist(resid(finals.lme), xlab = "Residuals of Linear mixed effects model", main = "Right skew when plotting the residuals of the linear mixed effects model")
dev.off()
```
```{r}
pdf(file = "Gamma_skew.pdf")
dev.off()
```

```{r}
pdf(file = "DataBoxplot.pdf")
boxplot(RxnTime ~ Year, data = men_pooled, xlab = "Year", ylab = "Reaction Time in seconds", main = "Men's Semifinal and Final Reaction Time Boxplot Data")
dev.off()
```

```{r}
pdf(file = "DataScatterplot.pdf")
plot(RxnTime ~ Year, data = men_pooled, xlab = "Year", ylab = "Reaction Time in seconds", main = "Men's Semifinal and Final Reaction Time Scatterplot Data")
dev.off()
```

```{r}
set.seed(1)
library(lme4)
pdf(file = "Men_Density_Year.pdf")
fit2 <- glmer(RxnTime ~ (1 | Year), data = men_pooled, family = Gamma(link = "log"))
fit0 <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))
sfit0 <- summary(fit0)
simfit <- function(fit2, n = 12000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x), main = "Men's Pooled With Only Year Effect") # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
legend("right", title = "Probability mean less than", legend = " 0.1 is 0.006847")
dev.off()
```


```{r}
set.seed(1)
library(lme4)
pdf(file = "Men_Density_Batch.pdf")
fit2 <- glmer(RxnTime ~ (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
fit0 <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))
sfit0 <- summary(fit0)
simfit <- function(fit2, n = 12000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x), main = "Men's Pooled With Only Batch Effect") # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "red") # fixed effect only
legend("right", title = "Probability mean less than", legend = " 0.1 is 0.0066115")
dev.off()
```


```{r}
set.seed(1)
library(lme4)
pdf(file = "Men_Density_Both.pdf")
fit2 <- glmer(RxnTime ~ (1 | Year) + (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
fit0 <- glm(RxnTime ~ 1, data = men_pooled, family = Gamma(link = "log"))
sfit0 <- summary(fit0)
simfit <- function(fit2, n = 10000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x), main = "Men's Pooled With Year and Batch Effect") # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "orange") # fixed effect only
legend("right", title = "Probability mean less than", legend = " 0.1 is 0")
dev.off()
```

```{r}
set.seed(1)
library(lme4)
pdf(file = "Women_Density_Year.pdf")
fit2 <- glmer(RxnTime ~ (1 | Year), data = women_pooled, family = Gamma(link = "log"))
fit0 <- glm(RxnTime ~ 1, data = women_pooled, family = Gamma(link = "log"))
sfit0 <- summary(fit0)
simfit <- function(fit2, n = 10000000) {
  vc <- as.data.frame(VarCorr(fit2))
  ## mu <- exp(coef(fit2)$Year[,]) ## using fitted random effects only
  z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
  mu <- exp(fixef(fit2) + z)
  shape <- 1 / vc$vcov[2]
  x <- rgamma(n, shape = shape, scale = mu / shape)
  x
}

x <- simfit(fit2)
mean(x < 0.1)
quantile(x, prob = c(.00001, .0001, .0005, .001))
## compare with and without random effect
plot(density(x), main = "Women's Pooled With Only Year Effect") # with random effect
curve(dgamma(x, shape = 1 / sfit0$dispersion,
             scale = exp(coef(fit0)) * sfit0$dispersion),
      0.08, 0.22, add = TRUE, col = "deeppink") # fixed effect only
legend("right", title = "Probability mean less than", legend = " 0.1 is 0.0042296")
dev.off()
```


```{r}
year_effect <- glmer(RxnTime ~ (1 | Year), data = men_pooled, family = Gamma(link = "log"))
batch_effect <- glmer(RxnTime ~ (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
both <- glmer(RxnTime ~ (1 | Year) + (1 | Batch), data = men_pooled, family = Gamma(link = "log"))
#anova(batch_effect, both)
summary(both)
```


```{r}
t.test(men_pooled$RxnTime[men_pooled$Year==2019],men_pooled$RxnTime[men_pooled$Year==2022])
```



```{r}
library(ggplot2)
ggplot(men_pooled, aes(x = Year, y = RxnTime, group = Year)) +
  geom_boxplot(fill = "orange1", color = "orangered4") +
  labs(x = "Year", y = "Reaction Time (s)") +
       scale_y_continuous(limits = c(0.1, 0.225),
                            breaks = seq(0.1, 0.225, 0.025)) +
  expand_limits(y = 0.1) + scale_x_continuous(limits = c(1998,2024),
                                              breaks = seq(1999, 2024, 2))
ggsave(filename="Boxplot.pdf", path = "../Manuscript", height = 4, width = 6)
```



```{r}
library(tidyr)
library(ggplot2)
nineteen <- read.csv("../Data/2019vs2022.csv")
#"C:\Users\ofior\Documents\Thesis\Data\2019vs2022.csv"
colnames(nineteen) <- c("Athlete", "Country", "2019 Heats", "2019 Semifinals", "2019 Finals", "2022 Heats", "2022 Semifinals", "2022 Finals")
nineteen <- nineteen[, -c(1,2)]
df_long <- tidyr::pivot_longer(nineteen, cols = everything(), names_to = "Column", values_to = "Time")
df_long$Column <- factor(df_long$Column, levels = c("2019 Heats", "2019 Semifinals", "2019 Finals", "2022 Heats", "2022 Semifinals", "2022 Finals"))
rank1 <- ggplot(df_long, aes(x = Column, y = Time)) +
  geom_point() +
  labs(y = "Reaction Time", x = "", title = "2019 vs 2022") +
  ylim(0.08, 0.22) +
  theme_minimal()
```

```{r}
library(tidyr)
library(ggplot2)
twentythree <- read.csv("../Data/2022vs2023.csv")
#"C:\Users\ofior\Documents\Thesis\Data\2019vs2022.csv"
colnames(twentythree) <- c("Athlete", "Country", "2022 Heats", "2022 Semifinals", "2022 Finals", "2023 Heats", "2023 Semifinals", "2023 Finals")
twentythree <- twentythree[, -c(1,2)]
df_long <- tidyr::pivot_longer(twentythree, cols = everything(), names_to = "Column", values_to = "Time")
df_long$Column <- factor(df_long$Column, levels = c("2022 Heats", "2022 Semifinals", "2022 Finals", "2023 Heats", "2023 Semifinals", "2023 Finals"))
rank2 <- ggplot(df_long, aes(x = Column, y = Time)) +
  geom_point() +
  labs(y = "Reaction Time", x = "", title = "2022 vs 2023") +
  ylim(0.08, 0.22) +
  theme_minimal()
```

```{r}
library(tidyr)
library(ggplot2)
national <- read.csv("../Data/NatVSWorld.csv")
#"C:\Users\ofior\Documents\Thesis\Data\2019vs2022.csv"
colnames(national) <- c("Athlete", "Country", "National Heats", "National Semifinals", "National Finals", "2023 Heats", "2023 Semifinals", "2023 Finals", "Data Source")
national <- national[, -c(1,2, 9)]
df_long <- tidyr::pivot_longer(national, cols = everything(), names_to = "Column", values_to = "Time")
df_long$Column <- factor(df_long$Column, levels = c("National Heats", "National Semifinals", "National Finals", "2022 Heats", "2022 Semifinals", "2022 Finals"))
rank3 <- ggplot(df_long, aes(x = Column, y = Time)) +
  geom_point() +
  labs(y = "Reaction Time", x = "", title = "2022 National vs International") +
  ylim(0.08, 0.22) +
  theme_minimal()
```

```{r}
library(gridExtra)
rank_scatter <- grid.arrange(rank1, rank2, rank3, ncol = 1)
ggsave(filename = "RankScatterPlots.pdf", path = "../Manuscript", plot=rank_scatter, height = 9, width = 7)
```


