---
title: "Descriptive_Stats"
author: "Owen Fiore"
date: "2023-05-21"
output: pdf_document
---

```{r}
nations <- read.csv("../Data/ClusrankNatvsWorld.csv")
colnames(nations) <- c("Time", "Athlete", "Year")
```

Keep the linewidth under 80. Otherwise the code lines are not complete in the
generated pdf files.

```{r}
library(clusrank)
clusWilcox.test(Time, group=Year, cluster = Athlete, data = nations,
                alternative = "greater", method = "ds")

clusWilcox.test(Time, group=Year, cluster = Athlete, data = nations,
                alternative = "greater", method = "ds", exact = TRUE)
```

```{r}
comp <- read.csv("../Data/Clusrank2019vs2022.csv")
#"C:\Users\ofior\Documents\Thesis\Data\2019vs2022.csv"
colnames(comp) <- c("Time", "Athlete", "Year")
#View(comp)
```

```{r}
library(clusrank)
clusWilcox.test(Time, group=Year, cluster = Athlete, data = comp,
                alternative = "greater", method = "ds")

clusWilcox.test(Time, group=Year, cluster = Athlete, data = comp,
                alternative = "greater", method = "ds", exact = TRUE)
```



```{r}
nations_noprelim <- read.csv("../Data/Clusrank2019vs2022PrelimsOnly.csv")
colnames(nations_noprelim) <- c("Time", "Athlete", "Year")
``` 

```{r}
library(clusrank)
clusWilcox.test(Time, group=Year, cluster = Athlete, data = nations_noprelim,
                alternative = "greater", method = "ds")
```
