---
title: "Simulate"
author: "Owen Fiore"
date: "2023-05-30"
output: pdf_document
---

```{}
The probability of observing a reaction time less than 0.01 is 0.0068649
The probability of observing a reaction time less than 0.095 is 0.0030386
The probability of observing a reaction time less than 0.09 is 0.00121


If we want to pick the barrier based on the reaction time a barrier of 0.08905, 1 in every 1001.603
If we want to pick the barrier based on the reaction time a barrier of 0.089, 1 in every 1012.248
If we want to pick the barrier based on the reaction time a barrier of 0.089057, 1 in every 999.9
If we want to pick the barrier based on the reaction time a barrier of 0.089056, 1 in every 1000.2
```




```{r}
library(lme4)
set.seed(1)
simulation <- function(model, base, RxnTime){
    simfit <- function(model, n = 10000000) {
    vc <- as.data.frame(VarCorr(model))
    ## mu <- exp(coef(model)$Year[,]) ## using fitted random effects only
    z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
    mu <- exp(fixef(model) + z)
    shape <- 1 / vc$vcov[2]
    x <- rgamma(n, shape = shape, scale = mu / shape)
    x
    }
  sbase <- summary(base)
  #print(sbase)
  x <- simfit(model)
  print(1/mean(x < RxnTime))
  print(quantile(x, prob = c(.00001, .0001, .0005, .001)))
  ## compare with and without random effect
  plot(density(x)) # with random effect
  curve(dgamma(x, shape = 1 / sbase$dispersion, 
               scale = exp(coef(base)) * sbase$dispersion), 
        0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
}
simulation(men_pooled_year_gamma_log, men_pooled_one_gamma_log, 0.089)
```

```{r}
library(lme4)
set.seed(1)
simulation <- function(model, base, prob){
    simfit <- function(model, n = 10000000) {
    vc <- as.data.frame(VarCorr(model))
    ## mu <- exp(coef(model)$Year[,]) ## using fitted random effects only
    z <- rnorm(n, sd = vc$sdcor[1]) #$ using generated random effects
    mu <- exp(fixef(model) + z)
    shape <- 1 / vc$vcov[2]
    x <- rgamma(n, shape = shape, scale = mu / shape)
    x
    }
  sbase <- summary(base)
  #print(sbase)
  x <- simfit(model)
  print(mean(x < 0.089))
  #print(quantile(x, prob = c(.00001, .0001, .0005, .001)))
  ## compare with and without random effect
  plot(density(x)) # with random effect
  curve(dgamma(x, shape = 1 / sbase$dispersion, 
               scale = exp(coef(base)) * sbase$dispersion), 
        0.08, 0.22, add = TRUE, col = "blue") # fixed effect only
}
simulation(men_pooled_year_gamma_log, men_pooled_one_gamma_log, 0.01)
```

```{r}
library(lme4)
set.seed(1)

simulation <- function(model, base, prob) {
  simfit <- function(model, n = 10000000) {
    vc <- as.data.frame(VarCorr(model))
    z <- rnorm(n, sd = vc$sdcor[1])
    mu <- exp(fixef(model) + z)
    shape <- 1 / vc$vcov[2]
    x <- rgamma(n, shape = shape, scale = mu / shape)
    x
  }

  sbase <- summary(base)
  x <- simfit(model)
  print(quantile(x, probs = prob))

  plot(density(x), main = "Density Plot", xlab = "RxnTime", ylab = "Density")
  curve(dgamma(x, shape = 1 / sbase$dispersion, scale = exp(coef(base)) * sbase$dispersion), 
        from = min(x), to = max(x), add = TRUE, col = "blue")
}

simulation(men_pooled_year_gamma_log, men_pooled_one_gamma_log, 0.001)
```



```{}
Currently mean(x < 0.089) returns a proportion of x values that are less than 0.089
We instead want to set the proportion to be some set value, ex: 0.001
```

