---
title: "Thesis"
author: "Owen Fiore"
date: "10/20/2022"
output: pdf_document
---

Reading in the Data
```{r}
times <- read.csv("../Data/ThesisData.csv")
View(times)
colnames(times) <- c("Year", "Type", "Time", "RxnTime", "Gender", "Batch")
```



#DataSets
```{r}
men_finals <- subset(times, Type == "F" & Gender == "M" & Time != 'DQ') # & Year < 2022)
women_finals <- subset(times, Type == "F" & Gender == "F" & Time != 'DQ')

men_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "M" & Time != 'DQ')
women_pooled <- subset(times, (Type == "F" | Type == "S") & Gender == "F" & Time != 'DQ')
```

#Models
```{r}
library(lme4)
model1 <- lmer(RxnTime ~ (1|Year), data = men_finals)
#finals.log <- lmer(log(RxnTime) ~ (1|Year), data = men_finals)
model0 <- lm(log(RxnTime) ~ 1, data = men_finals)
finals.gamma <- glmer(RxnTime ~ (1 | Year), data = men_finals, family = Gamma)
fit2 <- glmer(RxnTime ~ (1 | Year), data = men_finals, family = Gamma(link = "log"))
fit0<- glm(RxnTime ~ 1, data = men_finals, family = Gamma(link = "log"))
```

```{r}
model0 <- glm(log(RxnTime) ~ 1, data = men_pooled)
model1 <- lmer(log(RxnTime) ~ (1|Year), data = men_pooled)

#anova(model0, model1)
AIC(model0)
AIC(model1)
anova(fit0, fit2)
#AIC(fit0)
#AIC(fit2)
```


```{r}
qqnorm(resid(model0), main="Linear model")
qqnorm(resid(model1), main = "Log model")
qq(resid(finals.gamma),main="Gamma model no log")
qqnorm(resid(fit2), main = "Gamma model with log")
qqnorm(resid(fit0), main = "Gamma model with log without year effect")
#anova(finals.lme, finals.log, finals.gamma, fit2)
anova(model0, model1)
```


#Matched pairs t test
















t test comparing 2019 and 2022
```{r}
t.test(times$RxnTime[times$Year==2019],times$RxnTime[times$Year==2022])
```


Creates a Boxplot comparing 2019 and 2022
```{r}
#boxplot(times$RxnTime[times$Year==2019],times$RxnTime[times$Year==2022])
men_final <- subset(times, Gender == "M" & Type == "F")
women_final <- subset(times, Gender == "F" & Type == "F")
plot(RxnTime ~ Year, data = men_final, xlab = "Years")
plot(RxnTime ~ Year, data = women_final, xlab = "Years")

```

Creates a new data set of just finals and looks at the data from that
```{r}
library(ggplot2)
finals <- subset(times, Type == "F")
boxplot(RxnTime ~ Year, data = men_pooled, xlab = "Year", ylab = "Reaction Time in seconds", Main = "Men's Semifinal and Final Reaction Time Data")
```

```{r}
library(ggplot2)
plot(aggregate(men_pooled$RxnTime, list(men_pooled$Year), FUN = mean), xlab = "Year", ylab = "Reaction time in seconds", main = "Mean Reaction Time By Year")
```
```{r}
library(lme4)
finals.log <- lmer(log(RxnTime) ~ (1|Year), data = men_final)
#pdf(file = "Skew.pdf")
hist(resid(finals.log), xlab = "Residuals of Linear mixed effects model", main = "Right skew when plotting the residuals of the linear mixed effects model")
#dev.off()
```


```{r}
library(dplyr)
finals.aov <- aov(RxnTime ~ as.factor(Year), data = finals)
summary(finals.aov)
tuk.final <- TukeyHSD(finals.aov, conf.level = .95)
tkf <- as.data.frame(tuk.final[1])
tkf %>%filter(as.factor.Year..p.adj < 0.05)
#plot(tuk.final)
```


```{r}
residuals <- resid(finals.aov)
plot(finals$RxnTime, residuals, xlab="RxnTime", ylab="Residuals")
abline(0,0)
```

```{r}
library(lme4)
finals.log <- lmer(log(RxnTime) ~ (1|Year), data = men_final)
finals.lme <- lmer(RxnTime ~ (1|Year), data = men_final)
summary(finals.lme)
qqnorm(resid(finals.lme))
hist(resid(finals.log))
hist(resid(finals.lme))
qqnorm(resid(finals.log))
pnorm(0.1, mean = .148883, sd = sqrt(8.648*10^(-5)+3.719*10^(-4)))
qnorm(0.01,mean = .148883, sd = sqrt(8.648*10^(-5)+3.719*10^(-4)))
```


```{r}
library(hglm)
gamma.GLMM <- hglm(fixed = RxnTime ~ 1, random =   ~ 1|Year , data = finals,
                     family = Gamma(link = "log"), rand.family = gaussian(link = "identity"))
summary(gamma.GLMM)
plot(gamma.GLMM)
resid(gamma.GLMM)
```

```{r}
library(hglm)
gamma.conj <- hglm(fixed = RxnTime ~ Year, random =  ~ 1 | Year, data = finals,
                     family = Gamma(link = "inverse"), rand.family = inverse.gamma(link= "inverse"))
summary(gamma.conj)
plot(gamma.conj)

```

```{r}
library(hglm)
gamma.GLMM <- hglm(fixed = RxnTime ~ Year, random =  ~ 1 | Year, data = finals,
                     family = Gamma(link = "log"), rand.family = Gamma(link= "log"))
plot(gamma.GLMM, dev = "pdf", name = "First Gamma Model")
summary(gamma.GLMM)

```

```{r}
library(zeligverse)
z.out <- zelig(formula= ~ 1 + tag(RxnTime | Year),
data= finals, model="gamma.mixed")
```




```{}
library(lme4)
semi <- subset(times, Type == "S")
finals.lme <- lmer(RxnTime ~ (1|Year), data = semi)
summary(finals.lme)
qqnorm(resid(finals.lme))
hist(resid(finals.lme))
qqnorm(ranef(finals.lme))
```
```{}
library(lme4)
heat <- subset(times, Type == "H")
finals.lme <- lmer(RxnTime ~ (1|Year), data = heat)
summary(finals.lme)
qqnorm(resid(finals.lme))
hist(resid(finals.lme))
qqnorm(ranef(finals.lme))
str(ranef(finals.lme))
hist(ranef(finals.lme)$Year[,1])
qqnorm(ranef(finals.lme)$Year[,1])
qqline(ranef(finals.lme)$Year[,1])
```
```{r}
pnorm(0.1, mean = .157750, sd = sqrt(.0001228+0.0005937))
qnorm(0.01, mean = .157750, sd = sqrt(.0001228+0.0005937))
```

```{r}
my_fit <- lm(RxnTime ~ 1 , data = finals)
summary(my_fit)
```


```{r}
anova(finals.lme, my_fit)
```

```{r}
old <- subset(times, Year < 2020)
old.lme <- lmer(RxnTime ~ (1|Year), data = old)
summary(old.lme)
old_fit <- lm(RxnTime ~ 1 , data = old)
anova(old.lme, old_fit)


```

```{r}
model_coefs <- coef(old.lme)$Year

model_coefs
```


Plotting LME
```{r}
library(ggplot2)
model_coef_plot <- ggplot(data = old, 
       mapping = aes(x = Time, 
                     y = RxnTime, 
                     colour = Year)
       ) +
  scale_y_continuous(limits = c(180, 1020)) +
  scale_x_continuous(breaks = seq(1:10) - 1) +
  theme(legend.position = "top")

model_coef_plot
```



t test comparing men and women times in 2022
```{r}
men <- subset(times, Gender == "M")
women <- subset(times, Gender == "F")
t.test(men$RxnTime, women$RxnTime)

```

